### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fabier** [snimavat/recaptcha-spring-security#1]
Hi, there are compilation errors since package names changed in grails :

```
Fatal error during compilation org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/target/work/plugins/recaptcha-spring-security-0.1/./RecaptchaSpringSecurityGrailsPlugin.groovy: 5: unable to resolve class org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils
 @ line 5, column 1.
   import org.codehaus.groovy.grails.plugins.springsecurity.SpringSecurityUtils
```

It should now be :
`import grails.plugins.springsecurity.SpringSecurityUtils`

Can you make the change(s) please ? (there are other imports like this one)
Thanks !

(I'm using Grails 2.5.4)

**Comment by snimavat** [comment]
Okay, i will fix, or you can give a pull request and i will merge and release.

**Comment by fabier** [comment]
I'm working on it...

**Comment by fabier** [comment]
I'm unable to make this plugin work with instructions given and with correct imports, so I'm trying my luck with https://github.com/grygoriy/bruteforcedefender instead...
It seems that your imports are correct, but in my project imports are wrong... maybe this project is not in sync with grails plugin repository ? Or I have a configuration problem, I don't know, and I don't have much time to pass on this...
I have no clue why I can't make this plugin work...
I'm closing this issue.
